name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Frontend install
        working-directory: frontend
        run: |
          npm install

      - name: Frontend lint
        working-directory: frontend
        run: npm run lint --if-present

      - name: Frontend build
        working-directory: frontend
        env:
          NEXT_PUBLIC_API_URL: http://localhost:8004
        run: npm run build --if-present

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend requirements
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Backend import check
        working-directory: backend
        run: |
          python - << 'PY'
          import importlib
          import sys
          try:
              importlib.import_module('main')
              print('Backend import ok')
          except Exception as e:
              print('Backend import failed:', e)
              sys.exit(1)
          PY
